[package]
name = "consul-registrar"
version = "0.1.0"
authors = ["red <red.avtovo@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "^0.11.0", features=["json"]}
serde_json = "1.0.62"
tokio = { version = "1.2", features = ["full"] }