name: CI

on: [push]

env:
  DOCKER_IMAGE: j0rsa/consul-registrar

jobs:
  build_x86_64:
    name: Build X86_64
    runs-on: ubuntu-latest
    env:
      RUST_TARGET: x86_64-unknown-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          rustup target add ${RUST_TARGET}

#       Solves env substitution in args
      - name: Set Vars
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=6 ${{ github.sha }})
          echo ::set-output name=RUST_TARGET::${RUST_TARGET}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=${{ steps.vars.outputs.RUST_TARGET }}

      - name: Docker build
        run: |
          docker build --build-arg TARGET=${RUST_TARGET} -t ${DOCKER_IMAGE}:${{ steps.vars.outputs.sha_short }} .

      - name: Docker login
        if: github.ref == 'refs/heads/main'
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ${DOCKER_IMAGE}:${{ steps.vars.outputs.sha_short }} ${DOCKER_IMAGE}:latest
          docker push ${DOCKER_IMAGE}:${{ steps.vars.outputs.sha_short }}
          docker push ${DOCKER_IMAGE}:latest

  build_arm_v6:
    name: Build ARMv6
    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm/v6
      RUST_TARGET: arm-unknown-linux-gnueabihf
      DOCKER_FILE: Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Dependencies
        run: |
          sudo apt-get install gcc-arm-linux-gnueabihf -y
          rustup target add ${RUST_TARGET}

#       Solves env substitution in args
      - name: Set Vars
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=6 ${{ github.sha }})
          echo ::set-output name=RUST_TARGET::${RUST_TARGET}

      - name: Build
        uses: actions-rs/cargo@v1
        env:
          CC: arm-linux-gnueabihf-gcc
        with:
          command: build
          args: --release --all-features --target=${{ steps.vars.outputs.RUST_TARGET }}

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Docker build
        run: |
          docker buildx build \
          --platform ${DOCKER_TARGET_PLATFORM} \
          --tag ${DOCKER_IMAGE}:armv6_${{ steps.vars.outputs.sha_short }} \
          --build-arg TARGET=${RUST_TARGET} \
          --file ./${DOCKER_FILE} \
          --load .

      - name: Docker login
        if: github.ref == 'refs/heads/main'
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ${DOCKER_IMAGE}:armv6_${{ steps.vars.outputs.sha_short }} ${DOCKER_IMAGE}:armv6_latest
          docker push ${DOCKER_IMAGE}:armv6_${{ steps.vars.outputs.sha_short }}
          docker push ${DOCKER_IMAGE}:armv6_latest

  build_arm_v7:
    name: Build ARMv7
    runs-on: ubuntu-latest
    env:
      RUST_TARGET: armv7-unknown-linux-gnueabihf
      DOCKER_TARGET_PLATFORM: linux/arm/v7
      DOCKER_FILE: Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Dependencies
        run: |
          sudo apt-get install gcc-arm-linux-gnueabihf -y
          rustup target add ${RUST_TARGET}

#       Solves env substitution in args
      - name: Set Vars
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=6 ${{ github.sha }})
          echo ::set-output name=RUST_TARGET::${RUST_TARGET}

      - name: Build
        uses: actions-rs/cargo@v1
        env:
          CC: arm-linux-gnueabihf-gcc
        with:
          command: build
          args: --release --all-features --target=${{ steps.vars.outputs.RUST_TARGET }}

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Docker buildx build
        run: |
          docker buildx build \
          --platform ${DOCKER_TARGET_PLATFORM} \
          --tag ${DOCKER_IMAGE}:armv7_${{ steps.vars.outputs.sha_short }} \
          --build-arg TARGET=${RUST_TARGET} \
          --file ./${DOCKER_FILE} \
          --load .

      - name: Docker login
        if: github.ref == 'refs/heads/main'
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ${DOCKER_IMAGE}:armv7_${{ steps.vars.outputs.sha_short }} ${DOCKER_IMAGE}:armv7_latest
          docker push ${DOCKER_IMAGE}:armv7_${{ steps.vars.outputs.sha_short }}
          docker push ${DOCKER_IMAGE}:armv7_latest